### ISSUE TITLE
Todo vol2

### ISSUE THREAD

**Issue by merimaH** [merimaH/DRAOS2-Seminarski#2]
- [x] Registracija da dozvoljava druge formate
- [x] Potvrda naglasiti buttone
- [x] Prikaz slobodnih mjesta, da se prikazuju registracije ili imena vlasnika
- [x] Sortiranje tabele kod vlasnika po datumima
- [x] Samo 7 trenutno automobila moze biti u garazi
